// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;

namespace VideoLAN.LibVLC
{
    /// <summary>LibVLCEvent types</summary>
    public enum EventType
    {
        MediaMetaChanged = 0,
        MediaSubItemAdded = 1,
        MediaDurationChanged = 2,
        MediaParsedChanged = 3,
        MediaFreed = 4,
        MediaStateChanged = 5,
        MediaSubItemTreeAdded = 6,
        MediaPlayerMediaChanged = 256,
        MediaPlayerNothingSpecial = 257,
        MediaPlayerOpening = 258,
        MediaPlayerBuffering = 259,
        MediaPlayerPlaying = 260,
        MediaPlayerPaused = 261,
        MediaPlayerStopped = 262,
        MediaPlayerForward = 263,
        MediaPlayerBackward = 264,
        MediaPlayerEndReached = 265,
        MediaPlayerEncounteredError = 266,
        MediaPlayerTimeChanged = 267,
        MediaPlayerPositionChanged = 268,
        MediaPlayerSeekableChanged = 269,
        MediaPlayerPausableChanged = 270,
        MediaPlayerTitleChanged = 271,
        MediaPlayerSnapshotTaken = 272,
        MediaPlayerLengthChanged = 273,
        MediaPlayerVout = 274,
        MediaPlayerScrambledChanged = 275,
        MediaPlayerESAdded = 276,
        MediaPlayerESDeleted = 277,
        MediaPlayerESSelected = 278,
        MediaPlayerCorked = 279,
        MediaPlayerUncorked = 280,
        MediaPlayerMuted = 281,
        MediaPlayerUnmuted = 282,
        MediaPlayerAudioVolume = 283,
        MediaPlayerAudioDevice = 284,
        MediaPlayerChapterChanged = 285,
        MediaListItemAdded = 512,
        MediaListWillAddItem = 513,
        MediaListItemDeleted = 514,
        MediaListWillDeleteItem = 515,
        MediaListEndReached = 516,
        MediaListViewItemAdded = 768,
        MediaListViewWillAddItem = 769,
        MediaListViewItemDeleted = 770,
        MediaListViewWillDeleteItem = 771,
        MediaListPlayerPlayed = 1024,
        MediaListPlayerNextItemSet = 1025,
        MediaListPlayerStopped = 1026,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_start()</para>
        /// </remarks>
        MediaDiscovererStarted = 1280,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        MediaDiscovererEnded = 1281,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        RendererDiscovererItemAdded = 1282,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        RendererDiscovererItemDeleted = 1283,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaAdded = 1536,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaRemoved = 1537,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaChanged = 1538,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStarted = 1539,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStopped = 1540,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStatusInit = 1541,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStatusOpening = 1542,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStatusPlaying = 1543,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStatusPause = 1544,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStatusEnd = 1545,

        /// <remarks>
        /// <para>Useless event, it will be triggered only when calling</para>
        /// <para>libvlc_media_discoverer_stop()</para>
        /// </remarks>
        VlmMediaInstanceStatusError = 1546
    }

    /// <summary>Renderer item</summary>
    /// <remarks>
    /// <para>This struct is passed by a</para>
    /// <para>or deleted.</para>
    /// <para>An item is valid until the</para>
    /// <para>is called with the same pointer.</para>
    /// <para>libvlc_renderer_discoverer_event_manager()</para>
    /// </remarks>
    /// <summary>A LibVLC event</summary>
    public struct LibVLCEvent
    {
        public EventType Type;

        public IntPtr Sender;

        public EventUnion Union;

        public struct EventUnion
        {
            public MediaMetaChanged MediaMetaChanged;
            public MediaSubItemAdded MediaSubItemAdded;
            public MediaDurationChanged MediaDurationChanged;
            public MediaParsedChanged MediaParsedChanged;
            public MediaFreed MediaFreed;
            public MediaStateChanged MediaStateChanged;
            public MediaSubItemTreeAdded MediaSubItemTreeAdded;
            public MediaPlayerBuffering MediaPlayerBuffering;
            public MediaPlayerChapterChanged MediaPlayerChapterChanged;
            public MediaPlayerPositionChanged MediaPlayerPositionChanged;
            public MediaPlayerTimeChanged MediaPlayerTimeChanged;
            public MediaPlayerTitleChanged MediaPlayerTitleChanged;
            public MediaPlayerSeekableChanged MediaPlayerSeekableChanged;
            public MediaPlayerPausableChanged MediaPlayerPausableChanged;
            public MediaPlayerScrambledChanged MediaPlayerScrambledChanged;
            public MediaPlayerVideoOutChanged MediaPlayerVideoOutChanged;
            public MediaListItemAdded MediaListItemAdded;
            public MediaListWillAddItem MediaListWillAddItem;
            public MediaListItemDeleted MediaListItemDeleted;
            public MediaListWillDeleteItem MediaListWillDeleteItem;
            public MediaListPlayerNextItemSet MediaListPlayerNextItemSet;
            public MediaPlayerSnapshotTaken MediaPlayerSnapshotTaken;
            public MediaPlayerLengthChanged MediaPlayerLengthChanged;
            public VlmMediaEvent VlmMediaEvent;
            public MediaPlayerMediaChanged MediaPlayerMediaChanged;
            public EsChanged EsChanged;
            public VolumeChanged VolumeChanged;
            public AudioDeviceChanged AudioDeviceChanged;
            public RendererDiscovererItemAdded RendererDiscovererItemAdded;
            public RendererDiscovererItemDeleted RendererDiscovererItemDeleted;
        }
        
        public struct MediaMetaChanged
        {
            public Media.MetadataType MetaType;
        }

        public struct MediaSubItemAdded
        {
            public IntPtr NewChild;
        }

        public struct MediaDurationChanged
        {
            public long NewDuration;
        }

        public struct MediaParsedChanged
        {
            public int NewStatus;
        }

        public struct MediaFreed
        {
            public IntPtr MediaInstance;
        }
        
        public struct MediaStateChanged
        {
            public VLCState NewState;
        }
        
        public struct MediaSubItemTreeAdded
        {
            public IntPtr MediaInstance;
        }

        public struct MediaPlayerBuffering
        {
            public float NewCache;
        }

        public struct MediaPlayerChapterChanged
        {
            public int NewChapter;
        }

        public struct MediaPlayerPositionChanged
        {
            public float NewPosition;
        }

        public struct MediaPlayerTimeChanged
        {
            public long NewTime;
        }

        public struct MediaPlayerTitleChanged
        {
            public int NewTitle;
        }

        public struct MediaPlayerSeekableChanged
        {
            public int NewSeekable;
        }

        public struct MediaPlayerPausableChanged
        {
            public int NewPausable;
        }

        public struct MediaPlayerScrambledChanged
        {
            public int NewScrambled;
        }

        public struct MediaPlayerVideoOutChanged
        {
            public int NewCount;
        }

        public struct MediaListItemAdded
        {
            public IntPtr MediaInstance;
            public int Index;
        }

        public struct MediaListWillAddItem
        {
            public IntPtr MediaInstance;
            public int Index;
        }

        public struct MediaListItemDeleted
        {
            public IntPtr MediaInstance;
            public int Index;
        }

        public struct MediaListWillDeleteItem
        {
            public IntPtr MediaInstance;
            public int Index;
        }

        public struct MediaListPlayerNextItemSet
        {
            public IntPtr MediaInstance;
        }

        public struct MediaPlayerSnapshotTaken
        {
            public IntPtr Filename;
        }

        public struct MediaPlayerLengthChanged
        {
            public long NewLength;
        }

        public struct VlmMediaEvent
        {
            public IntPtr MediaName;
            public IntPtr InstanceName;
        }

        public struct MediaPlayerMediaChanged
        {
            public IntPtr NewMedia;
        }

        public struct EsChanged
        {
            public TrackType Type;
            public int Id;
        }

        public struct VolumeChanged
        {
            public float Volume;
        }

        public struct AudioDeviceChanged
        {
            public IntPtr Device;
        }

        public struct RendererDiscovererItemAdded
        {
            public IntPtr Item;
        }

        public struct RendererDiscovererItemDeleted
        {
            public IntPtr Item;
        }
    }
}
