//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibVLCSharp.Forms.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibVLCSharp.Forms.Shared.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:9.
        /// </summary>
        internal static string AspectRatio_16_9 {
            get {
                return ResourceManager.GetString("AspectRatio_16_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:3.
        /// </summary>
        internal static string AspectRatio_4_3 {
            get {
                return ResourceManager.GetString("AspectRatio_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best fit.
        /// </summary>
        internal static string AspectRatioBestFit {
            get {
                return ResourceManager.GetString("AspectRatioBestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string AspectRatioFill {
            get {
                return ResourceManager.GetString("AspectRatioFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit screen.
        /// </summary>
        internal static string AspectRatioFitScreen {
            get {
                return ResourceManager.GetString("AspectRatioFitScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string AspectRatioOriginal {
            get {
                return ResourceManager.GetString("AspectRatioOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio tracks.
        /// </summary>
        internal static string AudioTracks {
            get {
                return ResourceManager.GetString("AudioTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast to.
        /// </summary>
        internal static string CastTo {
            get {
                return ResourceManager.GetString("CastTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        internal static string ClosedCaptions {
            get {
                return ResourceManager.GetString("ClosedCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with media {0}.
        /// </summary>
        internal static string ErrorWithMedia {
            get {
                return ResourceManager.GetString("ErrorWithMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No track found.
        /// </summary>
        internal static string NoTrackFoundMessage {
            get {
                return ResourceManager.GetString("NoTrackFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0}.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIPE TO UNLOCK.
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video tracks.
        /// </summary>
        internal static string VideoTracks {
            get {
                return ResourceManager.GetString("VideoTracks", resourceCulture);
            }
        }
    }
}
